import { Client, LocalAuth, Message, MessageMedia } from 'whatsapp-web.js';
import Redis from 'ioredis';
import qrcodeTerminal from 'qrcode-terminal';
import * as qrcode from 'qrcode';

const REDIS_HOST = process.env.REDIS_HOST || '127.0.0.1';
const REDIS_PORT = process.env.REDIS_PORT || '6379';
const REDIS_URL = process.env.REDIS_URL || `redis://${REDIS_HOST}:${REDIS_PORT}`;

const pubClient = new Redis(REDIS_URL);
const subClient = new Redis(REDIS_URL);

// Channels
const CH_EVENTS = 'wa_events';
const CH_COMMANDS = 'wa_commands';

// Prevent Node from crashing on unhandled rejections from whatsapp-web.js
process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection at:', promise, 'reason:', reason);
});
process.on('uncaughtException', err => {
  console.error('Uncaught Exception:', err);
});

// Store multiple client instances for different sessions
const clients = new Map<string, Client>();
const qrCodes = new Map<string, string | null>();

/**
 * Publishes an event to the Redis event channel.
 * This is used to communicate state changes or incoming messages to the API Gateway.
 *
 * @param {string} sessionId - The unique identifier for the WhatsApp session.
 * @param {string} event - The name of the event (e.g., 'qr', 'ready', 'message').
 * @param {any} data - The payload associated with the event.
 */
function publishEvent(sessionId: string, event: string, data: any) {
  let outData = data;
  if (event === 'qr') {
    outData = { sessionId, qrCode: data };
  } else if (['ready', 'authenticated', 'disconnected'].includes(event)) {
    outData = { sessionId, status: event === 'disconnected' ? 'disconnected' : 'ready', ...data };
  } else {
    outData = { sessionId, ...data };
  }
  const payload = JSON.stringify({ event, data: outData });
  pubClient.publish(CH_EVENTS, payload);
  if (event !== 'message') {
    console.log(`[Event - ${sessionId}] ${event}`);
  }
}

/**
 * Publishes a reply to a specific RPC request back to the API Gateway.
 * Used for synchronous operations where the Gateway awaits a response.
 *
 * @param {string} req_id - The unique request ID generated by the Gateway.
 * @param {any} [data=null] - The successful response payload.
 * @param {string | null} [error=null] - Error message if the operation failed.
 */
function publishReply(req_id: string, data: any = null, error: string | null = null) {
  if (!req_id) return;
  const payload = JSON.stringify({ req_id, data, error });
  pubClient.publish('wa_replies', payload);
}

/**
 * Initializes a new WhatsApp Web client instance for a given session.
 * Configures event listeners to publish status updates and messages to Redis.
 *
 * @param {string} sessionId - The unique identifier for the WhatsApp session.
 * @returns {Client} The initialized WhatsApp Web.js client.
 */
function initializeClient(sessionId: string) {
  if (clients.has(sessionId)) {
    return clients.get(sessionId)!;
  }

  const client = new Client({
    authStrategy: new LocalAuth({ clientId: sessionId, dataPath: './sessions' }),
    puppeteer: {
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    },
  });

  client.on('qr', async (qr: string) => {
    qrcodeTerminal.generate(qr, { small: true });
    try {
      const dataUrl = await qrcode.toDataURL(qr);
      qrCodes.set(sessionId, dataUrl);
      publishEvent(sessionId, 'qr', dataUrl);
    } catch (error) {
      console.error(`Error generating QR code for session ${sessionId}:`, error);
    }
  });

  client.on('ready', () => {
    qrCodes.set(sessionId, null);
    const phone = client.info?.wid?.user;
    const pushname = client.info?.pushname;
    publishEvent(sessionId, 'ready', { status: 'ready', phone, pushname });
  });

  client.on('authenticated', () => {
    qrCodes.set(sessionId, null);
    publishEvent(sessionId, 'authenticated', { status: 'authenticated' });
  });

  client.on('auth_failure', (msg: string) => {
    qrCodes.set(sessionId, null);
    publishEvent(sessionId, 'auth_failure', { error: msg });
  });

  client.on('disconnected', (reason: string) => {
    qrCodes.set(sessionId, null);
    publishEvent(sessionId, 'disconnected', { reason });
    clients.delete(sessionId);
  });

  client.on('message', async (msg: Message) => {
    publishEvent(sessionId, 'message', {
      id: msg.id.id,
      from: msg.from,
      to: msg.to,
      body: msg.body,
      type: msg.type,
      timestamp: msg.timestamp,
      fromMe: msg.fromMe,
    });
  });

  clients.set(sessionId, client);
  return client;
}

// ─── Command Handler ────────────────────────────────────────────────────────

/**
 * Subscribe to the Redis command channel to listen for instructions
 * from the API Gateway (e.g., send message, create group, block contact).
 */
subClient.subscribe(CH_COMMANDS, (err, count) => {
  if (err) {
    console.error('Failed to subscribe: %s', err.message);
  } else {
    console.log(`[Redis] Subscribed to ${CH_COMMANDS} channel.`);
  }
});

subClient.on('message', async (channel, message) => {
  if (channel !== CH_COMMANDS) return;

  try {
    const payload = JSON.parse(message);
    console.log(`[Command] ${payload.action} for session ${payload.session_id}`);

    // Some commands don't require session_id, but most do
    const sessionId = String(payload.session_id);

    switch (payload.action) {
      case 'START_SESSION':
        if (clients.has(sessionId)) {
          console.log(`[Command] START_SESSION ignored: Session ${sessionId} is already running.`);
          break;
        }
        const clientToStart = initializeClient(sessionId);
        try {
          await clientToStart.initialize();
        } catch (e: any) {
          console.error('Failed to initialize:', e);
        }
        break;

      case 'GET_QR_CODE':
        publishReply(payload.req_id, qrCodes.get(sessionId) || null);
        break;

      case 'SEND_TEXT':
        if (clients.has(sessionId)) {
          try {
            const msg = await clients.get(sessionId)!.sendMessage(payload.to, payload.text);
            console.log(`Sent message to ${payload.to}`);
            if (payload.req_id) {
              const msgId = msg?.id?.id || msg?.id?._serialized || 'unknown';
              const timestamp = msg?.timestamp || Math.floor(Date.now() / 1000);
              console.log(`Publishing success reply for req_id: ${payload.req_id}`);
              publishReply(payload.req_id, {
                messageId: msgId,
                timestamp: timestamp,
              });
            } else {
              console.log(`No req_id provided for SEND_TEXT`);
            }
          } catch (e: any) {
            const errStr = e?.message || String(e) || 'Unknown error sending message';
            console.log(`Publishing error reply for req_id: ${payload.req_id}, error: ${errStr}`);
            if (payload.req_id) publishReply(payload.req_id, null, errStr);
          }
        } else if (payload.req_id) {
          publishReply(payload.req_id, null, 'Client not initialized');
        }
        break;

      case 'SEND_IMAGE':
      case 'SEND_VIDEO':
      case 'SEND_AUDIO':
      case 'SEND_DOCUMENT':
        if (clients.has(sessionId)) {
          try {
            const media = await MessageMedia.fromUrl(payload.url, { unsafeMime: true });
            let options: any = {};
            if (payload.caption) options.caption = payload.caption;
            if (payload.action === 'SEND_DOCUMENT') {
              options.sendMediaAsDocument = true;
              if (payload.filename) {
                media.filename = payload.filename;
              }
            } else if (payload.action === 'SEND_VIDEO') {
              if (!media.mimetype.startsWith('video/')) {
                media.mimetype = 'video/mp4';
              }
            }

            // sendAudio might need sendAudioAsVoice
            if (payload.action === 'SEND_AUDIO') options.sendAudioAsVoice = true;

            const msg = await clients.get(sessionId)!.sendMessage(payload.to, media, options);
            console.log(`Sent media to ${payload.to}`);
            if (payload.req_id) {
              const msgId = msg?.id?.id || msg?.id?._serialized || 'unknown';
              const timestamp = msg?.timestamp || Math.floor(Date.now() / 1000);
              publishReply(payload.req_id, { messageId: msgId, timestamp: timestamp });
            }
          } catch (e: any) {
            const errStr = e?.message || String(e) || 'Unknown error sending media';
            if (payload.req_id) publishReply(payload.req_id, null, errStr);
          }
        } else if (payload.req_id) {
          publishReply(payload.req_id, null, 'Client not initialized');
        }
        break;

      case 'LOGOUT':
        if (clients.has(sessionId)) {
          await clients.get(sessionId)!.logout();
          clients.delete(sessionId);
        }
        break;

      // --- RPC Commands ---
      case 'MARK_CHAT_UNREAD':
        if (clients.has(sessionId)) {
          try {
            const chat = await clients.get(sessionId)!.getChatById(payload.chatId);
            if (chat) {
              await chat.markUnread();
              if (payload.req_id) publishReply(payload.req_id, { success: true });
            } else {
              if (payload.req_id) publishReply(payload.req_id, null, 'Chat not found');
            }
          } catch (e: any) {
            const errStr = e?.message || String(e) || 'Unknown error marking chat unread';
            if (payload.req_id) publishReply(payload.req_id, null, errStr);
          }
        } else if (payload.req_id) {
          publishReply(payload.req_id, null, 'Client not initialized');
        }
        break;
      case 'GET_CONTACTS':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const contacts = await clients.get(sessionId)!.getContacts();
          publishReply(payload.req_id, contacts);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'GET_CONTACT_BY_ID':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const contact = await clients.get(sessionId)!.getContactById(payload.contact_id);
          publishReply(payload.req_id, contact);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'CHECK_NUMBER_STATUS':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const isRegistered = await clients.get(sessionId)!.isRegisteredUser(payload.number);
          publishReply(payload.req_id, isRegistered);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'BLOCK_CONTACT':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const contactToBlock = await clients.get(sessionId)!.getContactById(payload.contact_id);
          await contactToBlock.block();
          publishReply(payload.req_id, { success: true });
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'GET_GROUPS':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const chats = await clients.get(sessionId)!.getChats();
          const groups = chats
            .filter(c => c.isGroup)
            .map(g => ({
              id: g.id._serialized || (g.id as any),
              name: g.name,
              participants: (g as any).participants?.length || 0,
            }));
          publishReply(payload.req_id, groups);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'CREATE_GROUP':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const result = await clients.get(sessionId)!.createGroup(payload.name, payload.participants);
          publishReply(payload.req_id, result);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'ADD_PARTICIPANTS':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const chat = await clients.get(sessionId)!.getChatById(payload.group_id);
          if (chat.isGroup) {
            await (chat as any).addParticipants(payload.participants);
            publishReply(payload.req_id, { success: true });
          } else {
            throw new Error('Not a group');
          }
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'REMOVE_PARTICIPANTS':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const chat = await clients.get(sessionId)!.getChatById(payload.group_id);
          if (chat.isGroup) {
            await (chat as any).removeParticipants(payload.participants);
            publishReply(payload.req_id, { success: true });
          } else {
            throw new Error('Not a group');
          }
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'SET_GROUP_SUBJECT':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const chat = await clients.get(sessionId)!.getChatById(payload.group_id);
          if (chat.isGroup) {
            await (chat as any).setSubject(payload.subject);
            publishReply(payload.req_id, { success: true });
          } else {
            throw new Error('Not a group');
          }
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;
      case 'GET_CATALOG':
        if (!clients.has(sessionId)) return publishReply(payload.req_id, null, 'Client not initialized');
        try {
          const contact = await clients.get(sessionId)!.getContactById(payload.contact_id);
          const products = await (contact as any).getBusinessProfile();
          publishReply(payload.req_id, products);
        } catch (e: any) {
          publishReply(payload.req_id, null, e.message);
        }
        break;

      default:
        console.warn(`Unknown action: ${payload.action}`);
    }
  } catch (e) {
    console.error(`Error processing command:`, e);
  }
});

console.log('Worker is running. Waiting for START_SESSION command via Redis...');
